# Site specific settings
title: "MountSec"
name: "MountSec"
#keywords: "Key, words, about, this, website"
baseurl: "/"
url: "http://mountsec.info"
description: "~# Noobie hacker's blog"
cover: "/assets/img/cover.svg"
fanpage_id: ""

# Site general settings
lang: "en"
#lang_alternate: "pt_BR"
ssl: false # It will redirect to https

# Media
# Just the shortname:
# facebook: lampiaosec # Rigth
# facebook: facebook.com/lampiaosec # Wrong
disqus: 
twitter: 
facebook: 
github: 
google:

# Collection / Setting links for writeups
collections_dir: _posts/htb-writeups
collections_dir: _posts/vulnhub
    


# Build settings
markdown: kramdown
permalink: /:categories/:title/
